import { PrismaClient, UserRole, TenderStatus, RequirementCategory, DocumentStatus, ApplicationStatus, NotificationType } from '@prisma/client';
import bcrypt from 'bcryptjs';
const prisma=new PrismaClient();
const passwordHash=await bcrypt.hash('DemoPassword123!',12);

async function main(){
  await prisma.applicationDocument.deleteMany(); await prisma.complianceResult.deleteMany(); await prisma.emailVerificationCode.deleteMany(); await prisma.application.deleteMany(); await prisma.document.deleteMany(); await prisma.tenderRequirement.deleteMany(); await prisma.tender.deleteMany(); await prisma.notification.deleteMany(); await prisma.refreshToken.deleteMany(); await prisma.company.deleteMany(); await prisma.officerProfile.deleteMany(); await prisma.user.deleteMany();
  const officer=await prisma.user.create({data:{name:'Rahul Sharma',email:'rahul.sharma@cpcl.co.in',phone:'+919876543201',passwordHash,role:UserRole.OFFICER,emailVerified:true,phoneVerified:true,officerProfile:{create:{employeeId:'CPCL-EMP-1024',department:'Procurement',designation:'Procurement Officer'}}},include:{officerProfile:true}});
  const bidderData=[['Ananya Mehta','abc@demo.cpcl.in','+919876543211','ABC Engineering Pvt Ltd'],['Vikram Shah','xyz@demo.cpcl.in','+919876543212','XYZ Industries'],['Kiran Rao','delta@demo.cpcl.in','+919876543213','Delta Pumps'],['Meera Iyer','bharat@demo.cpcl.in','+919876543214','Bharat Engineering']];
  const bidders=[]; for(let i=0;i<bidderData.length;i++){const [name,email,phone,companyName]=bidderData[i];bidders.push(await prisma.user.create({data:{name,email,phone,passwordHash,role:UserRole.BIDDER,emailVerified:true,phoneVerified:true,company:{create:{companyName,cin:'U12345DL2020PTC123456',pan:'ABCDE1234F',gstin:'07ABCDE1234F1Z5',msmeNumber:'UDYAM-DL-00-1234567',contactEmail:email,contactPhone:phone,status:i===2?'BLACKLISTED':'ACTIVE',blacklistReason:i===2?'Seeded demonstration blacklist case':'',}}},include:{company:true}}));}
  const reqs=[{name:'PAN',category:RequirementCategory.STATUTORY},{name:'GST',category:RequirementCategory.STATUTORY},{name:'MSME',category:RequirementCategory.STATUTORY},{name:'Minimum Turnover ₹50 Cr',category:RequirementCategory.FINANCIAL},{name:'Minimum 3 Years Experience',category:RequirementCategory.EXPERIENCE},{name:'OEM Authorization',category:RequirementCategory.TECHNICAL},{name:'Technical Certification',category:RequirementCategory.TECHNICAL}];
  const t1=await prisma.tender.create({data:{tenderNumber:'CPCL/2026/001',title:'Supply of Industrial Pumps',description:'Supply, installation and commissioning of process pumps for CPCL refinery operations.',category:'Equipment & Machinery',startDate:new Date('2026-09-01'),closingDate:new Date('2026-10-15'),status:TenderStatus.ACTIVE,officerId:officer.officerProfile!.id,documentUrl:'/mock/uploads/CPCL_Industrial_Pumps_Tender.pdf',requirements:{create:reqs}}});
  await prisma.tender.create({data:{tenderNumber:'CPCL/2026/002',title:'Electrical Maintenance Equipment',description:'Supply of approved electrical maintenance equipment for refinery systems.',category:'Electrical & Instrumentation',startDate:new Date('2026-09-05'),closingDate:new Date('2026-10-22'),status:TenderStatus.ACTIVE,officerId:officer.officerProfile!.id,requirements:{create:reqs.slice(0,3)}}});
  await prisma.tender.create({data:{tenderNumber:'CPCL/2026/003',title:'Industrial Maintenance Services',description:'Annual maintenance services for CPCL industrial facilities.',category:'Civil / Construction / Maintenance',startDate:new Date('2026-08-20'),closingDate:new Date('2026-09-28'),status:TenderStatus.ACTIVE,officerId:officer.officerProfile!.id,requirements:{create:reqs.slice(0,5)}}});
  const scores=[94,82,61,89]; for(let i=0;i<bidders.length;i++){const b=bidders[i];const docTypes=['PAN','GST','MSME','OEM Certificate','Experience Certificate'];const docs=[];for(const type of docTypes.slice(0,i===2?2:4)){docs.push(await prisma.document.create({data:{companyId:b.company!.id,documentType:type,fileName:`${type.replaceAll(' ','_')}_${b.company!.companyName}.pdf`,fileUrl:'/mock/uploads/document.pdf',status:type==='Experience Certificate'&&i===0?DocumentStatus.REVIEW:DocumentStatus.VERIFIED}}));} await prisma.application.create({data:{tenderId:t1.id,companyId:b.company!.id,complianceScore:scores[i],status:ApplicationStatus.UNDER_REVIEW,submittedAt:new Date(`2026-09-${8+i}`),documents:{create:docs.slice(0,2).map(d=>({documentId:d.id}))}}});}
  await prisma.notification.createMany({data:[{userId:officer.id,title:'New bid received',message:'Four seeded bidders submitted applications for CPCL/2026/001',type:NotificationType.NEW_BID},{userId:bidders[0].id,title:'Application under review',message:'Your CPCL/2026/001 application is under review.',type:NotificationType.DOCUMENT_REVIEW}]});
  console.log('Seed complete. Officer: rahul.sharma@cpcl.co.in / DemoPassword123!'); console.log('Bidder: abc@demo.cpcl.in / DemoPassword123!');
}
main().catch(e=>{console.error(e);process.exit(1)}).finally(()=>prisma.$disconnect());
