import { prisma } from '../lib/prisma.js';
import { notFound } from '../utils/errors.js';

export async function createDocument(userId: string, data: any) { const company=await prisma.company.findUnique({where:{userId}}); if(!company)return notFound('Company profile not found'); return prisma.document.create({data:{companyId:company.id,documentType:data.documentType,fileName:data.fileName,fileUrl:data.fileUrl,status:data.status||'PENDING'}}); }
export async function listDocuments(userId: string) { const company=await prisma.company.findUnique({where:{userId}}); if(!company)return notFound('Company profile not found'); return prisma.document.findMany({where:{companyId:company.id},orderBy:{uploadedAt:'desc'}}); }
export async function getDocument(userId: string,id: string) { const company=await prisma.company.findUnique({where:{userId}}); const doc=await prisma.document.findFirst({where:{id,companyId:company?.id}}); if(!doc)return notFound('Document not found'); return doc; }
export async function updateDocument(userId: string,id: string,data:any) { const doc=await getDocument(userId,id); return prisma.document.update({where:{id:doc.id},data}); }
export async function deleteDocument(userId: string,id: string) { const doc=await getDocument(userId,id); await prisma.document.delete({where:{id:doc.id}}); }
export async function attachApplicationDocument(userId:string, applicationId:string, data:any) { const company=await prisma.company.findUnique({where:{userId}}); const app=await prisma.application.findFirst({where:{id:applicationId,companyId:company?.id}}); if(!app)return notFound('Application not found'); let documentId=data.documentId; if(!documentId && data.saveToDocumentVault){const doc=await prisma.document.create({data:{companyId:company!.id,documentType:data.documentType,fileName:data.fileName,fileUrl:data.fileUrl||'/mock/uploads/document.pdf',status:'PENDING'}});documentId=doc.id;} if(!documentId)return notFound('Document not found'); return prisma.applicationDocument.create({data:{applicationId,documentId,requirementId:data.requirementId}}); }
