import { Router } from 'express';
import { UserRole } from '@prisma/client';
import * as t from '../controllers/tender.controller.js';
import * as a from '../controllers/application.controller.js';
import * as d from '../controllers/document.controller.js';
import { requireAuth, requireRole } from '../middleware/auth.js';
import { validate } from '../middleware/validation.js';
import { asyncHandler } from '../utils/async-handler.js';
import * as av from '../validators/application.js';
import * as dv from '../validators/document.js';
import { singleDocumentUpload } from '../middleware/document-upload.js';
import * as td from '../controllers/tender-document.controller.js';
const router=Router(); router.use(requireAuth,requireRole(UserRole.BIDDER));
router.get('/tenders',asyncHandler(t.active));
router.get('/tenders/:id',asyncHandler(t.getActive));
router.get('/tenders/:tenderId/documents',asyncHandler(td.bidderList));
router.get('/tender-documents/:id/view',validate(dv.documentIdSchema),asyncHandler(td.bidderView));
router.get('/tender-documents/:id/download',validate(dv.documentIdSchema),asyncHandler(td.bidderDownload));
router.post('/tenders/:tenderId/apply',validate(av.applicationTenderSchema),asyncHandler(a.apply));
router.get('/applications',asyncHandler(a.bidderList));
router.get('/applications/:id',validate(av.applicationIdSchema),asyncHandler(a.bidderGet));
router.post('/documents',singleDocumentUpload,validate(dv.documentUploadSchema),asyncHandler(d.create));
router.get('/documents',asyncHandler(d.list));
router.get('/documents/:id/view',validate(dv.documentIdSchema),asyncHandler(d.view));
router.get('/documents/:id/download',validate(dv.documentIdSchema),asyncHandler(d.download));
router.get('/documents/:id',validate(dv.documentIdSchema),asyncHandler(d.get));
router.patch('/documents/:id',singleDocumentUpload,validate(dv.documentPatchSchema),asyncHandler(d.patch));
router.delete('/documents/:id',validate(dv.documentIdSchema),asyncHandler(d.remove));
router.post('/applications/:applicationId/documents',singleDocumentUpload,validate(av.applicationDocumentSchema),asyncHandler(d.attach));
export default router;
