import { Router } from 'express';
import { UserRole } from '@prisma/client';
import * as t from '../controllers/tender.controller.js';
import * as a from '../controllers/application.controller.js';
import { requireAuth, requireRole } from '../middleware/auth.js';
import { validate } from '../middleware/validation.js';
import { asyncHandler } from '../utils/async-handler.js';
import * as tv from '../validators/tender.js';
import * as av from '../validators/application.js';
const router=Router(); router.use(requireAuth,requireRole(UserRole.OFFICER));
router.post('/tenders',validate(tv.tenderCreateSchema),asyncHandler(t.create));
router.get('/tenders',asyncHandler(t.list));
router.get('/tenders/:id',asyncHandler(t.get));
router.patch('/tenders/:id',validate(tv.tenderPatchSchema),asyncHandler(t.patch));
router.post('/tenders/:id/publish',asyncHandler(t.publish));
router.post('/tenders/:id/close',asyncHandler(t.close));
router.delete('/tenders/:id',asyncHandler(t.remove));
router.post('/tenders/:tenderId/requirements',validate(tv.requirementCreateSchema),asyncHandler(t.addRequirement));
router.get('/tenders/:tenderId/requirements',asyncHandler(t.requirements));
router.patch('/requirements/:id',validate(tv.requirementPatchSchema),asyncHandler(t.patchRequirement));
router.delete('/requirements/:id',validate(tv.requirementDeleteSchema),asyncHandler(t.deleteRequirement));
router.get('/tenders/:tenderId/applications',asyncHandler(a.officerList));
router.get('/applications/:id',validate(av.applicationIdSchema),asyncHandler(a.officerGet));
router.post('/applications/:id/accept',validate(av.applicationIdSchema),asyncHandler(a.accept));
router.post('/applications/:id/reject',validate(av.rejectSchema),asyncHandler(a.reject));
router.post('/companies/:companyId/blacklist',validate(av.blacklistSchema),asyncHandler(a.blacklist));
export default router;
